## Operating on Data in Pandas

In [26]:
import pandas as pd
import numpy as np

In [27]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [28]:
df = pd.DataFrame(rng.randint(0, 10,(3, 4)),
columns=["A", "B", "C", "D"])
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [29]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [30]:
np.sin(df * np.pi / 4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

# Index Alignment

In [31]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                         'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                               'New York': 19651127}, name='population')

In [32]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [33]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [34]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [35]:
## Index alignment in DataFrame
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                         columns=list('AB'))
A

   A   B
0  1  11
1  5   1

In [36]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                         columns=list('BAC'))
B

   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [37]:
A + B

      A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [38]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

      A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

# Ufuncs: Operations Between DataFrame and Series

In [39]:
A = rng.randint(10, size=(3, 4))#
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]], dtype=int32)

In [40]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]], dtype=int32)

In [41]:
df = pd.DataFrame(A, columns=list("QRST"))
df - df.iloc[0]

   Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [42]:
df.subtract(df["R"], axis=0)

   Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [43]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [44]:
df - halfrow

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

In [49]:
df

   Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8