## Vectorized String Operations

### **Introducing Pandas String Operations**

In [1]:
import numpy as np
x = np.array([2, 3, 5, 7, 11, 13])
x * 2

array([ 4,  6, 10, 14, 22, 26])

In [3]:
data = ["peter", "Paul", "MARY", "gUIDO"]
[s.capitalize() for s in data]

['Peter', 'Paul', 'Mary', 'Guido']

In [4]:
import pandas as pd
names = pd.Series(data)
names

0    peter
1     Paul
2     MARY
3    gUIDO
dtype: object

In [5]:
names.str.capitalize()

0    Peter
1     Paul
2     Mary
3    Guido
dtype: object

## Tables of Pandas String Methods

In [6]:
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam',
                          'Eric Idle', 'Terry Jones', 'Michael Palin'])

In [7]:
# Methods similar to Python string methods
monte.str.lower()

0    graham chapman
1       john cleese
2     terry gilliam
3         eric idle
4       terry jones
5     michael palin
dtype: object

In [8]:
monte.str.len()

0    14
1    11
2    13
3     9
4    11
5    13
dtype: int64

In [10]:
# Boolean values: 
monte.str.startswith("T")

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [11]:
monte.str.split()

0    [Graham, Chapman]
1       [John, Cleese]
2     [Terry, Gilliam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Michael, Palin]
dtype: object

In [12]:
monte.str.extract('([A-Za-z]+)')

         0
0   Graham
1     John
2    Terry
3     Eric
4    Terry
5  Michael

In [13]:
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')

0    [Graham Chapman]
1                  []
2     [Terry Gilliam]
3                  []
4       [Terry Jones]
5     [Michael Palin]
dtype: object

In [14]:
monte.str[0:3]

0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: object

In [15]:
monte.str.split().str.get(-1)

0    Chapman
1     Cleese
2    Gilliam
3       Idle
4      Jones
5      Palin
dtype: object

#### **Indicator variables**

In [16]:
full_monte = pd.DataFrame({'name': monte,
                           'info': ['B|C|D', 'B|D', 'A|C', 'B|D', 'B|C',
                           'B|C|D']})
full_monte

             name   info
0  Graham Chapman  B|C|D
1     John Cleese    B|D
2   Terry Gilliam    A|C
3       Eric Idle    B|D
4     Terry Jones    B|C
5   Michael Palin  B|C|D

In [17]:
full_monte["info"].str.get_dummies("I")

   A|C  B|C  B|C|D  B|D
0    0    0      1    0
1    0    0      0    1
2    1    0      0    0
3    0    0      0    1
4    0    1      0    0
5    0    0      1    0

## Example: Recipe Database

In [25]:
with open(r"C:\Users\Admin\Desktop\github\python-data-science-handbook\data\recipeitems-latest.json") as f:
    line = f.readline()

pd.read_json(line).shape

C:\Users\Admin\AppData\Local\Temp\ipykernel_18696\4135986599.py:4: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(line).shape

(2, 12)

In [27]:
with open(r"C:\Users\Admin\Desktop\github\python-data-science-handbook\data\recipeitems-latest.json", "r") as f:
    data = (line.strip() for line in f)
    data_json = "[{0}]".format(",".join(data))
    recipes = pd.read_json(data_json)
recipes.shape

C:\Users\Admin\AppData\Local\Temp\ipykernel_18696\248654832.py:4: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  recipes = pd.read_json(data_json)

(2, 12)

In [28]:
recipes.iloc[0]

_id                           {'$oid': '5160756b96cc62079cc2db15'}
name                               Drop Biscuits and Sausage Gravy
ingredients      Biscuits\n3 cups All-purpose Flour\n2 Tablespo...
url              http://thepioneerwoman.com/cooking/2013/03/dro...
image            http://static.thepioneerwoman.com/cooking/file...
ts                                        {'$date': 1365276011104}
cookTime                                                     PT30M
source                                             thepioneerwoman
recipeYield                                                     12
datePublished                                           2013-03-11
prepTime                                                     PT10M
description      Late Saturday afternoon, after Marlboro Man ha...
Name: 0, dtype: object

In [29]:
recipes.ingredients.str.len().describe()

count      2.000000
mean     415.500000
std      142.128463
min      315.000000
25%      365.250000
50%      415.500000
75%      465.750000
max      516.000000
Name: ingredients, dtype: float64

In [30]:
recipes.name[np.argmax(recipes.ingredients.str.len())]

'Hot Roast Beef Sandwiches'

In [31]:
recipes.description.str.contains("[Bb]reakfast").sum()

np.int64(0)

In [32]:
recipes.ingredients.str.contains("[Cc]inamon").sum()

np.int64(0)

In [ ]:
spice_list = ['salt', 'pepper', 'oregano', 'sage', 'parsley',
                      'rosemary', 'tarragon', 'thyme', 'paprika', 'cumin']